### get all symbols
GET http://localhost:3000/stocks/symbols?query=qqq

### add like to symbols
POST http://localhost:3000/stocks/add-symbol
Content-Type: application/json

{
    "likedSymbols": ["amzn", "appl"]
}

### get all symbols data
GET http://localhost:3000/stocks/my-stocks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE4MDA3NzY2LCJleHAiOjE3MTgwMTEzNjZ9.tZu7wPH76n191LoIarFIV2Z7UoWVf3TzVaf0NN5p_Qg


### get spesifc symbol history
GET http://localhost:3000/stocks/stock-history?symbol=AMZN&days=1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE4MDA3NzY2LCJleHAiOjE3MTgwMTEzNjZ9.tZu7wPH76n191LoIarFIV2Z7UoWVf3TzVaf0NN5p_Qg

### get spesifc symbol history news
GET http://localhost:3000/stocks/news-history?symbol=FFIE&days=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE4MDA3NzY2LCJleHAiOjE3MTgwMTEzNjZ9.tZu7wPH76n191LoIarFIV2Z7UoWVf3TzVaf0NN5p_Qg

### get spesifc symbol opinion from huggingface
POST http://localhost:3000/stocks/ask-ai
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE4NTQ0MTg5LCJleHAiOjE3MTg1NDc3ODl9.abc9fdZ2ZbDNUQvH0yoNqVex1Vn1SUojxNEXzrxfb5A


{
    "symbol": "SPY"
}



